//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsList
    {
        public int Id { get; set; }
        public int CinemaRoomId { get; set; }
        public int SeansId { get; set; }
        public int LineId { get; set; }
        public int PlaceId { get; set; }
        public bool Sold { get; set; }
    }
}
